version: '2'
services:
  main:
    build: .
    environment:
      APPLICATION_NAME: 'onboarding'
      NODE_ENV: "development"
      MYSQL_PASSWORD: "notSecurePa55w0rd"
      MYSQL_DATABASE: "bnp"
      MYSQL_USER: "root"
      MYSQL_DIALECT: "mysql"
      MYSQL_SERVICE_NAME: "mysql"
      POPULATE_DATA: "false"
      EXTERNAL_HOST: 52.174.28.41
      EXTERNAL_PORT: 8080
      CONSUL_HOST: ${CONSUL_HOST}
      PORT: ${PORT}
      HOST_IP: ${HOST_IP}
    depends_on:
      - mysql
      - registrator
    volumes:
      - .:/home/node/onboarding
    labels:
      - 'SERVICE_NAME=onboarding'
      - 'SERVICE_TAGS=external,kong'
    extra_hosts:
      - 'consul:${HOST_IP}'
    ports:
      - '${PORT}:${PORT}'
    command: "npm run dev"

  mysql:
    image: "mysql:5.6"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "notSecurePa55w0rd"
      MYSQL_DATABASE: "bnp"
    depends_on:
      - registrator

  consul:
    image: consul:latest
    network_mode: host
    ports:
      - '8400:8400'
      - '8500:8500'
      - '8600:53/udp'
      - "53:8600/udp"
      - "53:8600"
    labels:
      SERVICE_IGNORE: 'true'  # Do not add any of Consul's services to Consul's service discovery registry.
    command: [agent, '-server', '-ui', '-bootstrap-expect=1', '-bind=${HOST_IP}', '-client=0.0.0.0']

  registrator:
    image: gliderlabs/registrator:latest
    network_mode: host
    depends_on:
     - consul
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock
    command: ['consul://${HOST_IP}:8500']

  nginx:
    image: gr4per/nginx-rp:latest
    ports:
      - '8080:8080'
    depends_on:
      - main
      - registrator
    environment:
      PORT: '8080'
    labels:
      SERVICE_NAME: 'nginx'
