version: '2'
services:
  campaigns:
    build: .
    environment:
      APPLICATION_NAME: 'campaigns'
      NODE_ENV: "development"
      PORT: '${CAMPAIGNS_PORT}'
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DIALECT: ${MYSQL_DIALECT}
      MYSQL_SERVICE_NAME: "mysql"
      CONSUL_HOST: "consul"
      POPULATE_DATA: "true"
    depends_on:
      - registrator
      - mysql
    volumes:
      - .:/campaigns
      - /campaigns/node_modules
    labels:
      SERVICE_NAME: 'campaigns'
    expose:
      - '${CAMPAIGNS_PORT}'

#  bnp:
#    build: ./../bnp
#    depends_on:
#     - mysql
#     - suppliers
#     - registrator
#     - campaigns
#    labels:
#     - 'SERVICE_NAME=bnp'
#    ports:
#     - "3000:3000"
#    environment:
#      NODE_ENV: "development"
#      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      DB_NAME: ${MYSQL_DATABASE}
#      DB_USER: ${MYSQL_USER}
#      DB_DIALECT: ${MYSQL_DIALECT}
#      DB_SERVICE_NAME: "mysql"
#      CONSUL_HOST: "consul"
#    volumes:
#     - ./../bnp:/home/node/bnp
#     - /home/node/bnp/node_modules
#
#  suppliers:
#    image: "supplier-dir"
#    ports:
#     - '3001:3001'
#    depends_on:
#     - mysql
#     - registrator
#    environment:
#      NODE_ENV: "production"
#      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      DB_NAME: ${MYSQL_DATABASE}
#      DB_USER: ${MYSQL_USER}
#      DB_DIALECT: ${MYSQL_DIALECT}
#      DB_SERVICE_NAME: "mysql"
#      CONSUL_HOST: "consul"
#    labels:
#     - 'SERVICE_NAME=suppliers'  # Service name used by Registrator for adding to Consul's service discovery registry.

  mysql:
    image: "mysql:5.6"
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - registrator

  consul:
    command: -bootstrap -ui
    image: gliderlabs/consul-server
    ports:
     - "8400:8400"
     - "8500:8500"
     - "8600:53/udp"

  registrator:
    image: gliderlabs/registrator
    command: -internal consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul

  nginx:
    build: ./../nginx-rp
    ports:
     - '${EXTERNAL_PORT}:${NGINX_PORT}'
    depends_on:
     - campaigns
    environment:
      PORT: '${NGINX_PORT}'
      DOCKER_CONTAINERS_HOST_EXTERNAL_PORT: ${EXTERNAL_PORT}
    expose:
     - '${NGINX_PORT}'
    labels:
      SERVICE_NAME: 'nginx'
