version: '3'
services:
  main:
    environment:
      APPLICATION_NAME: 'onboarding'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REDIS_AUTH: ${REDIS_AUTH}
      GATEWAY_SCHEME: $GATEWAY_SCHEME
      GATEWAY_IP: $GATEWAY_IP
      GATEWAY_PORT: $GATEWAY_PORT
      SERVICE_3002_CHECK_HTTP: /api/health/check
      SERVICE_3002_CHECK_INTERVAL: 15s
      SERVICE_3002_CHECK_TIMEOUT: 3s
    depends_on:
      - mysql
      - redis
      - registrator
      - einvoice-send
      - notification
      - acl
      - customer
      - blob
    labels:
      - 'SERVICE_3002_CHECK_HTTP=/api/health/check'
      - 'SERVICE_3002_CHECK_INTERVAL=15s'
      - 'SERVICE_3002_CHECK_TIMEOUT=3s'
      - 'SERVICE_3002_NAME=onboarding'
      - 'SERVICE_TAGS=external,kong'
    ports:
      - '3002:3002'
    volumes_from:
      - source
  test:
     image: ocbesbn/selenium
     network_mode: host
     environment:
       APPLICATION_NAME: 'onboarding' #please make sure those envs are the same as in main
       EXTERNAL_HOST: localhost
       EXTERNAL_PORT: 8080
       DISPLAY: ':1.0'
     extra_hosts:
       - 'consul:${HOST_IP}'
     depends_on:
       - main
     volumes:
       - ./test:/test
       - /tmp:/home/seluser/result
     shm_size: 8G
     tmpfs:
       - /run
       - /tmp
