version: '3'
services:
  main:
    build: .
    network_mode: host
    environment:
      APPLICATION_NAME: 'onboarding'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      EXTERNAL_HOST: 52.174.28.41
      EXTERNAL_PORT: 8080
      REDIS_AUTH: ${REDIS_AUTH}
      HOST_IP: ${HOST_IP}
    depends_on:
      - mysql
      - redis
      - registrator
    volumes:
      - ./src:/home/node/onboarding/src
#      - ../react-components:/var/tmp/base/node_modules/ocbesbn-react-components
    labels:
      - 'SERVICE_NAME=onboarding'
      - 'SERVICE_TAGS=external,kong'
    extra_hosts:
      - 'consul:${HOST_IP}'
    ports:
      - '3002:3002'
    command: 'npm run dev'

  postgres:
    image: postgres:9.4
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: $POSTGRES_DB
      POSTGRES_DB: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    depends_on:
      - registrator

  user:
    image: opuscapita/user:dev
#    build: ../user
#    volumes:
#      - ../user:/home/node/user
    depends_on:
     - mysql
     - consul
     - registrator
    labels:
      SERVICE_NAME: 'user'
    extra_hosts:
     - 'consul:${HOST_IP}'
    environment:
      PORT: 3008
      HOST_IP: $HOST_IP
      MYSQL_DATABASE: $MYSQL_DATABASE
      REDIS_AUTH: $REDIS_AUTH
      USER_NAME: 'user'
      PASSWORD: 'svc_user'
      CLIENT_KEY: $CLIENT_KEY
      CLIENT_SECRET: $CLIENT_SECRET
      SCOPE: $SCOPE
    ports:
     - '3008:3008'
    command: 'npm run dev'

  apigw:
    image: ocbesbn/api-gw:dev
#    volumes:
#      - .:/usr/local/kong/logs
    environment:
      KONG_DATABASE: 'postgres'
      KONG_PG_HOST: $KONG_PG_HOST
      KONG_PG_PORT: $KONG_PG_PORT
      APP_HOST: $HOST_IP
      APP_HOST_PROTOCOL: $APP_HOST_PROTOCOL
      APP_HOST_PORT: $APP_HOST_PORT
      GATEWAY_SCHEME: $GATEWAY_SCHEME
      GATEWAY_IP: $GATEWAY_IP
      GATEWAY_PORT: $GATEWAY_PORT
      GATEWAY_CALLBACK: $GATEWAY_CALLBACK
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      LOG_PORT: 5000
      LOG_HOST: $LOG_HOST
      HOST: $HOST_IP
      REDIS_HOST: $HOST_IP # TODO: remove after api-gw is using config
      REDIS_PORT: 6379 # TODO: remove after api-gw is using config
      REDIS_AUTH: $REDIS_AUTH # TODO: remove after api-gw is using config
      SERVICE_8001_NAME: 'kong-api'
      SERVICE_8080_NAME: 'kong'
    ports:
      - '8080:8080'
      - '8443:8443'
      - '8001:8001'
      - '7946:7946'
      - '7946:7946/udp'
    depends_on:
      - postgres
      - mysql

  auth:
    image: opuscapita/auth:dev
#    build: ../auth
#    volumes:
#      - ../auth:/home/node/auth
    ports:
     - '$APP_HOST_PORT:$APP_HOST_PORT'
    environment:
      HOST_IP: $HOST_IP
      NODE_ENV: $NODE_ENV
      APP_HOST: '0.0.0.0'
      APP_HOST_PROTOCOL: $APP_HOST_PROTOCOL
      APP_HOST_PORT: $APP_HOST_PORT
      GATEWAY_SCHEME: $GATEWAY_SCHEME
      GATEWAY_IP: $GATEWAY_IP
      GATEWAY_PORT: $GATEWAY_PORT
      GATEWAY_CALLBACK: $GATEWAY_CALLBACK
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      REDIS_AUTH: ${REDIS_AUTH}
      USER_NAME: 'auth'
      PASSWORD: 'svc_auth'
      CLIENT_KEY: $CLIENT_KEY
      CLIENT_SECRET: $CLIENT_SECRET
      SCOPE: $SCOPE
    depends_on:
      - apigw
    extra_hosts:
      - 'consul:${HOST_IP}'
    command: 'npm run dev'

  acl:
    image: opuscapita/acl:dev
    labels:
      - 'SERVICE_NAME=acl'
      - 'SERVICE_TAGS=external,kong'
    environment:
      PORT: 3013
      HOST_IP: ${HOST_IP}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
     - '3013:3013'
    depends_on:
      - apigw
    command: 'npm run dev'

  api-registry:
    image: ocbesbn/api-registrator:dev
#    build: ../api-registrator
    ports:
      - '$API_REGISTRY_PORT:$API_REGISTRY_PORT'
    environment:
      AUTH_SERVER: $AUTH_SERVER
      AUTH_SERVER_PORT: $AUTH_SERVER_PORT
      API_REGISTRY_PORT: $API_REGISTRY_PORT
      GATEWAY_CALLBACK: $GATEWAY_CALLBACK
    depends_on:
      - apigw

  email:
    image: opuscapita/email:dev
#    build: ../email
#    volumes:
#      - ../email:/home/node/email
    environment:
      NODE_ENV: 'production'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REDIS_AUTH: ${REDIS_AUTH}
      HOST_IP: ${HOST_IP}
    extra_hosts:
      - 'consul:${HOST_IP}'
    depends_on:
      - registrator
    command: 'npm run dev:production'

#  maildev:
#    image: djfarrelly/maildev
#    ports:
#      - '1080:80' # UI PORT
#      - '1025:25' # SMTP PORT
#    labels:
#      SERVICE_IGNORE: 'true'

  mysql:
    image: 'mysql:5.6'
    command: ['--character-set-server=utf8', '--collation-server=utf8_general_ci']
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - registrator

  redis:
    image: 'ocbesbn/redis'
    environment:
      REDIS_AUTH: $REDIS_AUTH
    depends_on:
      - registrator
    ports:
      - $REDIS_PORT:$REDIS_PORT

  consul:
    command: -bootstrap -ui
    image: gliderlabs/consul-server
    labels:
     - 'SERVICE_NAME=consul'
    ports:
     - '8400:8400'
     - '8500:8500'
     - '53:8600/udp'
     - '53:8600'

  registrator:
    image: gliderlabs/registrator
    command: -ip ${HOST_IP} consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul
