version: '2'
services:
  main:
    build: .
    network_mode: host
    environment:
      APPLICATION_NAME: 'onboarding'
      NODE_ENV: "development"
      MYSQL_PASSWORD: "notSecurePa55w0rd"
      MYSQL_DATABASE: "bnp"
      MYSQL_USER: "root"
      MYSQL_DIALECT: "mysql"
      MYSQL_SERVICE_NAME: "mysql"
      POPULATE_DATA: "false"
      EXTERNAL_HOST: 52.174.28.41
      EXTERNAL_PORT: 8080
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_AUTH: ${REDIS_AUTH}
      CONSUL_HOST: ${CONSUL_HOST}
      PORT: ${PORT}
      HOST_IP: ${HOST_IP}
    depends_on:
      - mysql
      - redis
      - registrator
    volumes:
      - .:/home/node/onboarding
    labels:
      - 'SERVICE_NAME=onboarding'
      - 'SERVICE_TAGS=external,kong'
    extra_hosts:
      - 'consul:${HOST_IP}'
    ports:
      - '${PORT}:${PORT}'
    command: "npm run dev"

  mysql:
    image: "mysql:5.6"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "notSecurePa55w0rd"
      MYSQL_DATABASE: "bnp"
    depends_on:
      - registrator
  
  redis:
    image: "ocbesbn/redis"
    environment:
      REDIS_AUTH: $REDIS_AUTH
    depends_on:
      - registrator
    ports:
      - $REDIS_PORT:$REDIS_PORT
  
  consul:
    command: -bootstrap -ui
    image: gliderlabs/consul-server
    labels:
     - 'SERVICE_NAME=consul'
    ports:
     - "8400:8400"
     - "8500:8500"
     - "53:8600/udp"
     - "53:8600"

  registrator:
    image: gliderlabs/registrator
    command: -ip ${HOST_IP} consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul

  nginx:
    image: gr4per/nginx-rp:dev
    ports:
     - '8080:8080'
    depends_on:
     - main
     - registrator

    environment:
      PORT: '8080'
      DOCKER_CONTAINERS_HOST_EXTERNAL_PORT: 8080
    expose:
     - '8080'
    labels:
      SERVICE_NAME: 'nginx'