version: '2'
services:
  campaigns:
    build: .
    environment:
      APPLICATION_NAME: 'campaigns'
      NODE_ENV: "development"
      PORT: "3002"
      MYSQL_PASSWORD: "notSecurePa55w0rd"
      MYSQL_DATABASE: "bnp"
      MYSQL_USER: "root"
      MYSQL_DIALECT: "mysql"
      MYSQL_SERVICE_NAME: "mysql"
      CONSUL_HOST: "consul"
      POPULATE_DATA: "false"
      API_KEY: "key-f5c8fa8c7b7691bf5b21d1971e822c8e"
      DOMAIN: "sandboxa30099c9392e43768348abce5da1b1ad.mailgun.org"
      EXTERNAL_HOST: 52.174.28.41
      EXTERNAL_PORT: 8080

    depends_on:
      - registrator
      - mysql
    volumes:
      - .:/campaigns
      - /campaigns/node_modules
    labels:
      - 'SERVICE_NAME=campaigns'
      - 'SERVICE_TAGS=external'
    ports:
     - "3002:3002"

  idpro:
    container_name: idpro
    build:
      context: ./idpro
      args:
          APP_HOST: '0.0.0.0'
          APP_HOST_PROTOCOL: $APP_HOST_PROTOCOL
          APP_HOST_PORT: $APP_HOST_PORT
    ports:
     - "$APP_HOST_PORT:$APP_HOST_PORT"
    environment:
      NODE_ENV: $NODE_ENV
      MYSQL_PORT: $MYSQL_PORT
      MYSQL_DIALECT: 'mysql'
      MYSQL_SERVICE_NAME: $MYSQL_HOST
      APP_HOST: '0.0.0.0'
      APP_HOST_PROTOCOL: $APP_HOST_PROTOCOL
      APP_HOST_PORT: $APP_HOST_PORT
      GATEWAY_SCHEME: $GATEWAY_SCHEME
      GATEWAY_IP: $GATEWAY_IP
      GATEWAY_PORT: $GATEWAY_PORT
      GATEWAY_CALLBACK: $GATEWAY_CALLBACK
    depends_on:
      - registrator
      - mysql
    labels:
      SERVICE_NAME: 'idpro'
    volumes:
      - .:/idpro
      - /idpro/node_modules



  mysql:
    image: "mysql:5.6"
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "notSecurePa55w0rd"
      MYSQL_DATABASE: "bnp"
    depends_on:
      - registrator

  consul:
    command: -bootstrap -ui
    image: gliderlabs/consul-server
    ports:
     - "8400:8400"
     - "8500:8500"
     - "8600:53/udp"

  registrator:
    image: gliderlabs/registrator
    command: -ip ${HOST} consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul

  nginx:
    image: gr4per/nginx-rp:latest
    ports:
     - '8080:8080'
    depends_on:
     - campaigns
     - registrator
     - idpro

    environment:
      PORT: '8080'
      DOCKER_CONTAINERS_HOST_EXTERNAL_PORT: 8080
    expose:
     - '8080'
    labels:
      SERVICE_NAME: 'nginx'
