version: '3'
services:
  test:
     image: ocbesbn/selenium
     network_mode: host
     environment:
       APPLICATION_NAME: 'onboarding' #please make sure those envs are the same as in main
       EXTERNAL_HOST: localhost
       EXTERNAL_PORT: 8080
       DISPLAY: ':1.0'
     extra_hosts:
       - 'consul:${HOST_IP}'
     depends_on:
       - main
     volumes:
       - ./test:/test
       - /tmp:/home/seluser/result
     shm_size: 8G
     tmpfs:
       - /run
       - /tmp
