type: object
displayName: Campaign
description: Contains all campaign details.
properties:
  campaignId:
    type: string
    description: Unique identifier.
  campaignType:
    type: string
    description: Custom type of campaign.
  countryId:
    type: string
    description: Campaign target country identifier.
  customerId:
    type: string
    description: Campaign owning customer.
  description:
    type: string
    description: Detailed description.
  emailTemplate:
    type: string
    description: Email template used in sent emails.
  endsOn:
    type: string
    description: Date campaign ends.
  startOn:
    type: string
    description: Date campaign starts.
  invitationCode:
    type: string
    description: Custom invitation code to track transitions and controll access.
  landingpageTemplate:
    type: string
    description: Template used for landing page.
  languageId:
    type: string
    description: Campaign target language.
  status:
    type: string
    description: Describes current status of campaign.
