#%RAML 1.0
title: Campaign Contacts information
baseUri: /api/campaigns/{campaignId}
types:
  TestType:
    type: object
    properties:
      id: number
      optional?: string
      expanded:
        type: object
        properties:
          count: number
/contacts:
  description: API to load the campaign's contacts list.
  uriParameters:
    campaignId:
      displayName: Campaign ID
      type: string
      required: true
      pattern: \w{3}
  get:
    headers:
      Accept-Language	:
        type: string
        description: Header containing a sorted list of accepted languages.
        required: false
        example: de, en-gb;q=0.8, en;q=0.7
    responses:
      200:
        description: |
          |
            It will return the Contact's array of objects belongs to Campaign.
        body:
          application/json:
            type: array
            example: |
              [{
                "id": 1,
                "email":"Andy@gmail.com",
                "campaignId":"FirstCampaign",
                "status":"sent",
                "companyName":"OC",
                "contactFirstName":"Andy",
                "contactLastName":"Andy",
                "address":"Contact Address",
                "city":"SIn",
                "country":"UK",
                "commercialRegisterNo":"s",
                "taxIdentNo":"s",
                "vatIdentNo":"s",
                "dunsNo":"s",
                "telephone":"3456789056"
              },{
                "id": 2,
                "email":"Andy@gmail.com",
                "campaignId":"FirstCampaign",
                "status":"new",
                "companyName":"OC",
                "contactFirstName":"Andy",
                "contactLastName":"Andy",
                "address":"Contact Address",
                "city":"SIn",
                "country":"UK",
                "commercialRegisterNo":"s",
                "taxIdentNo":"s",
                "vatIdentNo":"s",
                "dunsNo":"s",
                "telephone":"3456789056"
              }]
  post:
    description: API to add new contact for Camapign.
    headers:
      Accept-Language	:
        type: string
        description: Header containing a sorted list of accepted languages.
        required: false
        example: de, en-gb;q=0.8, en;q=0.7
    body:
      application/json:
        type: object
        example: |
          {
            "email":"s@md.com",
            "campaignId":"asd",
            "status":"new",
            "companyName":"s",
            "contactFirstName":"s",
            "contactLastName":"s",
            "address":"s",
            "city":"s",
            "country":"s",
            "commercialRegisterNo":"s",
            "taxIdentNo":"s",
            "vatIdentNo":"s",
            "dunsNo":"s",
            "telephone":"s",
            "supplierId":"s"
          }

    responses:
      201:
        description: |
          |
            It will return the newly created Campaign's contact object.
        body:
          application/json:
            type: object
            example: |
              {
                "id":1,
                "email":"s@md.com",
                "campaignId":"asd",
                "status":"new",
                "companyName":"s",
                "contactFirstName":"s",
                "contactLastName":"s",
                "address":"s",
                "city":"s",
                "country":"s",
                "commercialRegisterNo":"s",
                "taxIdentNo":"s",
                "vatIdentNo":"s",
                "dunsNo":"s",
                "telephone":"s",
                "supplierId":"s",
                "cell":null,
                "lastStatusChange":null
              }
  /{email}:
    description: Update and Delete contacts using email Id.
    uriParameters:
      campaignId:
        displayName: Campaign ID
        type: string
        required: true
        pattern: \w{3}        
      email:
        displayName: Email ID
        type: string
        required: true
        pattern: \w{3}
    put:
      description: To update contact by email.
      headers:
        Accept-Language	:
          type: string
          description: Header containing a sorted list of accepted languages.
          required: false
          example: de, en-gb;q=0.8, en;q=0.7
      body:
        application/json:
          example: |
            {
              "id": 1,
              "email":"Andy@gmail.com",
              "campaignId":"FirstCampaign",
              "status":"sent",
              "companyName":"OC",
              "contactFirstName":"Andy",
              "contactLastName":"Andy",
              "address":"Contact Address",
              "city":"NY",
              "country":"UK",
              "commercialRegisterNo":"s",
              "taxIdentNo":"s",
              "vatIdentNo":"s",
              "dunsNo":"s",
              "telephone":"3456789056"
            }
      responses:
        200:
          description: |
            |
              Return current updated contact's object.
          body:
            application/json:
              example: |
                {
                  "id": 1,
                  "email":"Andy@gmail.com",
                  "campaignId":"FirstCampaign",
                  "status":"sent",
                  "companyName":"OC",
                  "contactFirstName":"Andy",
                  "contactLastName":"Andy",
                  "address":"Contact Address",
                  "city":"NY",
                  "country":"UK",
                  "commercialRegisterNo":"s",
                  "taxIdentNo":"s",
                  "vatIdentNo":"s",
                  "dunsNo":"s",
                  "telephone":"3456789056"
                }
    delete:
      description: To delete camapign by email.
      headers:
        Accept-Language	:
          type: string
          description: Header containing a sorted list of accepted languages.
          required: false
          example: de, en-gb;q=0.8, en;q=0.7
      responses:
        200:
          description: |
            |
              Return empty object on success.

          body:
            application/json:
              example: |
                {}
