#%RAML 1.0
title: Campaign Information
baseUri: /api/campaigns
types:
  TestType:
    type: object
    properties:
      id: number
      optional?: string
      expanded:
        type: object
        properties:
          count: number
/campaigns:
  get:
    description: To search campaign.
    headers:
      Accept-Language	:
        type: string
        description: Header containing a sorted list of accepted languages.
        required: false
        example: de, en-gb;q=0.8, en;q=0.7
    queryParameters:
      campaignId:
        type: string
        description: To search campaign by ID.
        required: false
      status:
        type: string
        description: To search campaign by status.
        required: false
      campaignType:
        type: string
        description: To search campaign by campaign type.
        required: false

    responses:
      200:
        body:
          application/json:
            example: |
              [{
                "campaignId" : "1",
                "campaignType" : "SupplierOnboarding",
                "description" : "asd",
                "endsOn" : "2017-02-28T00:00:00.000Z",
                "owner" : "john.doe@ncc.com",
                "startsOn" : "2017-03-08T00:00:00.000Z",
                "status" : "new"
              },{
                "campaignId" : "2",
                "campaignType" : "SupplierOnboarding",
                "description" : "Campaign for documenttaion",
                "endsOn" : "2017-02-28T00:00:00.000Z",
                "owner" : "john.doe@ncc.com",
                "startsOn" : "2017-03-08T00:00:00.000Z",
                "status" : "inprogress"
              }]

  post:
    description: To create new campaign.
    headers:
      Accept-Language	:
        type: string
        description: Header containing a sorted list of accepted languages.
        required: false
        example: de, en-gb;q=0.8, en;q=0.7
    body:
      application/json:
        example: |
          {
            "campaignId" : "asd",
            "campaignType" : "SupplierOnboarding",
            "description" : "asd",
            "endsOn" : "2017-02-28T00:00:00.000Z",
            "owner" : "john.doe@ncc.com",
            "startsOn" : "2017-03-08T00:00:00.000Z",
            "status" : "new"
          }
    responses:
      201:
        description: |
          |
            Return created campaign object on success.

        body:
          application/json:
            example: |
              {
                "message" : "Not found",
                "campaignId" : "asd",
                "campaignType" : "SupplierOnboarding",
                "description" : "asd",
                "endsOn" : "2017-02-28T00:00:00.000Z",
                "owner" : "john.doe@ncc.com",
                "startsOn" : "2017-03-08T00:00:00.000Z",
                "status" : "new"
              }
  / {campaignId}:
    description: |
      Retrieve,Update or Delete individual campaign.
    uriParameters:
      campaignId:
        displayName: Campaign ID
        type: string
        required: true
        pattern: \w{3}
    get:
      description: It will return single campaign object according to id.
      headers:
        Accept-Language	:
          type: string
          description: Header containing a sorted list of accepted languages.
          required: false
          example: de, en-gb;q=0.8, en;q=0.7
      responses:
        200:
          description: |
            |
              Object representing a single campaign item.

          body:
            application/json:
              example: |
                {
                  "campaignId": "2344",
                  "description": "Camapaign description",
                  "startsOn": 12/03/2017,
                  "endsOn": "15/03/2017",
                  "status": "complete",
                  "campaignType": 'SupplierOnboarding',
                  "owner": 'john',
                  "companyId": 'xyz'
                }

        404:
          body:
            application/json:
              example: |
                {
                  "message" : "Not found"
                }
  /{campaignId}:
    uriParameters:
      campaignId:
        displayName: Campaign ID
        type: string
        required: true
        pattern: \w{3}
    delete:
      description: To delete camapign by ID.
      headers:
        Accept-Language	:
          type: string
          description: Header containing a sorted list of accepted languages.
          required: false
          example: de, en-gb;q=0.8, en;q=0.7
      responses:
        200:
          description: |
            |
              Return empty object on success.

          body:
            application/json:
              example: |
                {}

    put:
      description: To update campaign by campaignId.
      headers:
        Accept-Language	:
          type: string
          description: Header containing a sorted list of accepted languages.
          required: false
          example: de, en-gb;q=0.8, en;q=0.7
      body:
        application/json:
          type: object
          example:
            {
              "campaignId": "2344",
              "description": "Updated Camapaign description",
              "startsOn": 12/03/2017,
              "endsOn": "15/03/2017",
              "status": "complete",
              "campaignType": 'SupplierOnboarding',
              "owner": 'john',
              "companyId": 'xyz'
            }
      responses:
        200:
          body:
            application/json:
              type: object
              example:
                {
                  "campaignId": "2344",
                  "description": "Updated Camapaign description",
                  "startsOn": 12/03/2017,
                  "endsOn": "15/03/2017",
                  "status": "complete",
                  "campaignType": 'SupplierOnboarding',
                  "owner": 'john',
                  "companyId": 'xyz'
                }
