export const CAMPAIGNS_LOAD_START = 'CAMPAIGNS_LOAD_START';
export const CAMPAIGNS_LOAD_SUCCESS = 'CAMPAIGNS_LOAD_SUCCESS';
export const CAMPAIGNS_LOAD_ERROR = 'CAMPAIGNS_LOAD_ERROR';

export const CAMPAIGN_CREATE_START = 'CAMPAIGN_CREATE_START';
export const CAMPAIGN_CREATE_SUCCESS = 'CAMPAIGN_CREATE_SUCCESS';
export const CAMPAIGN_CREATE_ERROR = 'CAMPAIGN_CREATE_ERROR';

export const CAMPAIGN_UPDATE_START = 'CAMPAIGN_UPDATE_START';
export const CAMPAIGN_UPDATE_SUCCESS = 'CAMPAIGN_UPDATE_SUCCESS';
export const CAMPAIGN_UPDATE_ERROR = 'CAMPAIGN_UPDATE_ERROR';

export const CAMPAIGN_DELETE_START = 'CAMPAIGN_DELETE_START';
export const CAMPAIGN_DELETE_SUCCESS = 'CAMPAIGN_DELETE_SUCCESS';
export const CAMPAIGN_DELETE_ERROR = 'CAMPAIGN_DELETE_ERROR';

export const CAMPAIGN_STARTING_START = 'CAMPAIGN_STARTING_START';
export const CAMPAIGN_STARTING_SUCCESS = 'CAMPAIGN_STARTING_SUCCESS';
export const CAMPAIGN_STARTING_ERROR = 'CAMPAIGN_STARTING_ERROR';

export const CAMPAIGN_FIELDS = [
  'campaignId',
  'description',
  'startsOn',
  'endsOn',
  'status',
  'campaignType',
  'owner'
];

export const ONBOARDING_CAMPAIGN_FIELDS = [
  'email',
  'firstName',
  'lastName',
  'transition',
  'campaignId',
  'contactId'
];
