export const CAMPAIGNS_LOAD_START = 'CAMPAIGNS_LOAD_START';
export const CAMPAIGNS_LOAD_SUCCESS = 'CAMPAIGNS_LOAD_SUCCESS';
export const CAMPAIGNS_LOAD_ERROR = 'CAMPAIGNS_LOAD_ERROR';

export const CAMPAIGN_CREATE_START = 'CAMPAIGN_CREATE_START';
export const CAMPAIGN_CREATE_SUCCESS = 'CAMPAIGN_CREATE_SUCCESS';
export const CAMPAIGN_CREATE_ERROR = 'CAMPAIGN_CREATE_ERROR';