export const CAMPAIGN_CONTACTS_LOAD_START = 'CAMPAIGN_CONTACTS_LOAD_START';
export const CAMPAIGN_CONTACTS_LOAD_SUCCESS = 'CAMPAIGN_CONTACTS_LOAD_SUCCESS';
export const CAMPAIGN_CONTACTS_LOAD_ERROR = 'CAMPAIGN_CONTACTS_LOAD_ERROR';

export const CAMPAIGN_CONTACT_UPDATE_START = 'CAMPAIGN_CONTACT_UPDATE_START';
export const CAMPAIGN_CONTACT_UPDATE_SUCCESS = 'CAMPAIGN_CONTACT_UPDATE_SUCCESS';
export const CAMPAIGN_CONTACT_UPDATE_ERROR = 'CAMPAIGN_CONTACT_UPDATE_ERROR';

export const CAMPAIGN_CONTACT_CREATE_START = 'CAMPAIGN_CONTACT_CREATE_START';
export const CAMPAIGN_CONTACT_CREATE_SUCCESS = 'CAMPAIGN_CONTACT_CREATE_SUCCESS';
export const CAMPAIGN_CONTACT_CREATE_ERROR = 'CAMPAIGN_CONTACT_CREATE_ERROR';

export const CAMPAIGN_CONTACT_DELETE_START = 'CAMPAIGN_CONTACT_DELETE_START';
export const CAMPAIGN_CONTACT_DELETE_SUCCESS = 'CAMPAIGN_CONTACT_DELETE_SUCCESS';
export const CAMPAIGN_CONTACT_DELETE_ERROR = 'CAMPAIGN_CONTACT_DELETE_ERROR';

export const CAMPAIGN_CONTACTS_IMPORT_START = 'CAMPAIGN_CONTACTS_IMPORT_START';
export const CAMPAIGN_CONTACTS_IMPORT_SUCCESS = 'CAMPAIGN_CONTACTS_IMPORT_SUCCESS';
export const CAMPAIGN_CONTACTS_IMPORT_ERROR = 'CAMPAIGN_CONTACTS_IMPORT_ERROR';
export const RESET_IMPORT_INFO = 'RESET_IMPORT_INFO';

export const SELECT_CAMPAIGN_CONTACT = 'SELECT_CAMPAIGN_CONTACT';
export const REMOVE_CAMPAIGN_CONTACT_SELECTION = 'REMOVE_CAMPAIGN_CONTACT_SELECTION';

export const CAMPAIGN_CONTACT_FIELDS = [
  'email',
  'campaignId',
  'status',
  'companyName',
  'contactFirstName',
  'contactLastName',
  'address',
  'dunsNo',
  'telephone',
  'cell',
  'supplierId'
];
