export const CAMPAIGN_CONTACT_LOAD_START = 'CAMPAIGN_CONTACT_LOAD_START';
export const CAMPAIGN_CONTACT_LOAD_SUCCESS = 'CAMPAIGN_CONTACT_LOAD_SUCCESS';
export const CAMPAIGN_CONTACT_LOAD_ERROR = 'CAMPAIGN_CONTACT_LOAD_ERROR';