export const SEARCH_CAMPAIGN_FORM = 'SEARCH_CAMPAIGN_FORM';
export const CREATE_CAMPAIGN_FORM = 'CREATE_CAMPAIGN_FORM';
export const EDIT_CAMPAIGN_FORM = 'EDIT_CAMPAIGN_FORM';
export const ONBOARDING_CAMPAIGN_FORM = 'ONBOARDING_CAMPAIGN_FORM';

export const EDIT_CAMPAIGN_CONTACT_FORM = 'EDIT_CAMPAIGN_CONTACT_FORM';
export const CREATE_CAMPAIGN_CONTACT_FORM = 'CREATE_CAMPAIGN_CONTACT_FORM';
